# 生产环境配置文件
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.201.130:8848 # nacos地址
    gateway:
      # 网关路由配置
      routes:
        - id: user-service # 自定义路由id，只要唯一即可
          uri: lb://user-service # 目标路由地址（lb+服务名称是负载均衡，如果写http就是固定地址）
          predicates: # 路由断言规则
            - Path=/api/user/** # 按照路径匹配
  application:
    name: gateway # 服务名称
  main:
    web-application-type: reactive
server:
  port: 8101 # 网关端口

# 生产环境关闭knife4j文档
knife4j:
  gateway:
    enabled: false