spring:
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 # nacos地址
    gateway:
      # 网关路由配置
      routes:
        - id: user-service # 自定义路由id，只要唯一即可
          uri: lb://user-service # 目标路由地址（lb+服务名称是负载均衡，如果写http就是固定地址）
          predicates: # 路由断言规则
            - Path=/api/user/** # 按照路径匹配
  application:
    name: gateway # 服务名称
  main:
    web-application-type: reactive
server:
  port: 8101 # 网关端口

# knife4j网关聚合接口文档,生产环境请关闭
knife4j:
  gateway:
    # ① 第一个配置，开启gateway聚合组件
    enabled: true
    # ② 第二行配置，设置聚合模式采用discover服务发现的模式，开启后可无需手动配置子服务路由
    strategy: discover
    discover:
      # ③ 第三行配置，开启discover模式
      enabled: true
      # ④ 第四行配置，聚合子服务全部为openapi3规范的文档,springboot3只支持openapi3
      version: openapi3
      # 可配置需要排除的微服务(excluded-services:)
