spring:
  application:
    name: user-service
  profiles:
    active: dev
  # swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session
  session:
    store-type: redis
    # 30天
    timeout: 2592000
    redis:
      namespace: cloud-demo # 设置key值
  # 数据库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud_demo
    username: root
    password: yhx
  servlet:
    multipart:
      max-file-size: 10MB
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  # Redis
  data:
    redis:
      database: 1
      host: localhost
      port: 6379
      timeout: 5000
      password: 123456
server:
  address: 0.0.0.0
  port: 8102
  # 本服务地址
  servlet:
    context-path: /api/user
    # cookie 30 天
    session:
      cookie:
        max-age: 2592000
        path: /api
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0

# 接口文档配置
# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      # 配置接口文档扫描包路径
      packages-to-scan: com.yen.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
    # 展示实体类列表
    enable-swagger-models: true
    swagger-model-name: 实体类列表
    # 关闭页脚
    enable-footer: false