spring:
  application:
    name: business-service
  # swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session
  session:
    store-type: redis
    # 30天
    timeout: 2592000
  # 数据库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/springcloud_demo
    username: root
    password: 123456
  servlet:
    multipart:
      max-file-size: 10MB
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.201.130:8848
  # Redis
  data:
    redis:
      database: 1
      host: localhost
      port: 6379
      timeout: 5000
      password: yinhongxi
server:
  address: 0.0.0.0
  port: 8103
  # 本服务地址
  servlet:
    context-path: /api/business
    # cookie 30 天
    session:
      cookie:
        max-age: 2592000
        path: /api
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0

# 关闭接口文档
knife4j:
  enable: false
springdoc:
  api-docs:
    enabled: false